#!/bin/bash

# Sets up a local PHP installation using a PPA, but does not set up Composer.

source 'output.sh'

PHP_VERSION='8.1'
echo 'Installing local PHP …'
sudo add-apt-repository deb https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main
sudo apt update
sudo apt install -y \
"php${PHP_VERSION}-cli" \
"php${PHP_VERSION}-common" \
"php${PHP_VERSION}-xdebug" \
"php${PHP_VERSION}-xml" \
"php${PHP_VERSION}-curl" \
"php${PHP_VERSION}-fpm" \
"php${PHP_VERSION}-mysql" \
"php${PHP_VERSION}-xmlrpc" \
"php${PHP_VERSION}-mbstring" \
"php${PHP_VERSION}-imap" \
"php${PHP_VERSION}-opcache" \
"php${PHP_VERSION}-intl" \
"php${PHP_VERSION}-zip" \
"libapache2-mod-php{PHP_VERSION}"
success 'Done.'
linefeed